# Register without referral code
POST localhost:8082/api/v1/imps/p2a
Content-Type: application/json

{
   "BeneAccNo"       : "111234567890",
   "BeneIFSC"        : "DLXB0000092",
   "Amount"          : "1",
   "TranRefNo"       : "123132128834556",
   "PaymentRef"      : "FTTransferP2P",
   "RemName"         : "RenName",
   "RemMobile"       : "9860001122",
   "RetailerCode"    : "rcode",
   "PassCode"        : "a9a42043d31945c0bbb87f6fc5d0b31e",
   "TransactionDate" : "20150707171319"

}

###